CREATE TABLE
IF NOT EXISTS projects
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK
(name <> ''),
  priority INTEGER not NULL,
  description text,
  deliverydate date NOT NULL
);

CREATE TABLE
IF NOT EXISTS tasks
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK
(name <> ''),
  done BOOLEAN,
  projectid INTEGER REFERENCES projects
(id)
);

INSERT INTO projects
  (name, priority, description, deliverydate)
VALUES('Make a web App', 1, 'Using Js', '2022-05-12');

INSERT INTO projects
  (name, priority, description, deliverydate)
VALUES('Make an App', 1, 'Using Python', '2022-05-20');

INSERT INTO projects
  (name, priority, description, deliverydate)
VALUES('Make a Desktop App', 2, 'Using Python', '2022-06-25');

--INSERT tasks data
INSERT INTO tasks
  ( name, done, projectid)
VALUES('Download VueJs', false, 1);

INSERT INTO tasks
  ( name, done, projectid)
VALUES('Create UI Web', false, 1);

INSERT INTO tasks
  ( name, done, projectid)
VALUES('Download Flask', false, 2);

INSERT INTO tasks
  ( name, done, projectid)
VALUES('Desing UI', false, 2);